//                           _       _
// __      _____  __ ___   ___  __ _| |_ ___
// \ \ /\ / / _ \/ _` \ \ / / |/ _` | __/ _ \
//  \ V  V /  __/ (_| |\ V /| | (_| | ||  __/
//   \_/\_/ \___|\__,_| \_/ |_|\__,_|\__\___|
//
//  Copyright © 2016 - 2026 Weaviate B.V. All rights reserved.
//
//  CONTACT: hello@weaviate.io
//

// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// IndexUpdateRangeable index update rangeable
//
// swagger:model IndexUpdateRangeable
type IndexUpdateRangeable struct {

	// When true, cancels the in-flight reindex task targeting this property's rangeable index.
	Cancel bool `json:"cancel,omitempty"`

	// When true, removes any leftover on-disk runtime-reindex state (sentinel .migrations/<dir> and partial __reindex/__ingest sidecar buckets) for this property's rangeable index. Use this to clear silent half-state left behind by a backup taken during an in-flight migration. The handler refuses (409) if a STARTED reindex task is targeting this (collection, property, rangeable) tuple — issue cancel:true first. Idempotent: if nothing is on disk, the call returns 200 with "nothing to clean" in the response body. The schema's indexRangeFilters flag is unchanged.
	Cleanup bool `json:"cleanup,omitempty"`

	// enabled
	Enabled bool `json:"enabled,omitempty"`

	// When true, rebuilds the rangeable index from the existing filterable bucket (same source-of-truth as enable-rangeable).
	Rebuild bool `json:"rebuild,omitempty"`
}

// Validate validates this index update rangeable
func (m *IndexUpdateRangeable) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this index update rangeable based on context it is used
func (m *IndexUpdateRangeable) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *IndexUpdateRangeable) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *IndexUpdateRangeable) UnmarshalBinary(b []byte) error {
	var res IndexUpdateRangeable
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
