//                           _       _
// __      _____  __ ___   ___  __ _| |_ ___
// \ \ /\ / / _ \/ _` \ \ / / |/ _` | __/ _ \
//  \ V  V /  __/ (_| |\ V /| | (_| | ||  __/
//   \_/\_/ \___|\__,_| \_/ |_|\__,_|\__\___|
//
//  Copyright © 2016 - 2026 Weaviate B.V. All rights reserved.
//
//  CONTACT: hello@weaviate.io
//

// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// IndexUpdateFilterable index update filterable
//
// swagger:model IndexUpdateFilterable
type IndexUpdateFilterable struct {

	// When true, cancels the in-flight reindex task targeting this property's filterable index.
	Cancel bool `json:"cancel,omitempty"`

	// When true, removes any leftover on-disk runtime-reindex state (sentinel `.migrations/<dir>` and partial `__reindex`/`__ingest` sidecar buckets) for this property's filterable index. Use this to clear silent half-state left behind by a backup taken during an in-flight migration (see runtime-reindex PR description and 0-weaviate-issues#215 B6). The handler refuses (409) if a STARTED reindex task is targeting this (collection, property, filterable) tuple — issue `cancel:true` first. Idempotent: if nothing is on disk, the call returns 200 with `"nothing to clean"` in the response body. The schema's `indexFilterable` flag is unchanged.
	Cleanup bool `json:"cleanup,omitempty"`

	// enabled
	Enabled bool `json:"enabled,omitempty"`

	// rebuild
	Rebuild bool `json:"rebuild,omitempty"`

	// Change the tokenization used by the filterable index on this text/text[] property. Only valid when the property already has a filterable index. Use this for filterable-only properties; for properties that ALSO have a searchable index, prefer searchable.tokenization since it retokenizes both buckets in a single coordinated migration.
	Tokenization string `json:"tokenization,omitempty"`
}

// Validate validates this index update filterable
func (m *IndexUpdateFilterable) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this index update filterable based on context it is used
func (m *IndexUpdateFilterable) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *IndexUpdateFilterable) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *IndexUpdateFilterable) UnmarshalBinary(b []byte) error {
	var res IndexUpdateFilterable
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
